/**D3 json数据 */
 var mockData = '{"result":{"nodes":[{"id":"IV","parentNodeId":"","group":"","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"assess_2","parentNodeId":"IV","group":"孤立性骨转移","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"assess_1","parentNodeId":"IV","group":"孤立性脑或肾上腺转移","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"strategy_1_3","parentNodeId":"assess_1","group":"PS>=2","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"strategy_1_3_a1","parentNodeId":"strategy_1_3","group":"ALK融合基因阳性","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"strategy_1_3_a3","parentNodeId":"strategy_1_3","group":"无驱动基因、非鳞癌","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"strategy_1_3_a4","parentNodeId":"strategy_1_3","group":"无驱动基因、鳞癌","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"strategy_1_3_a2","parentNodeId":"strategy_1_3","group":"ROS1融合基因阳性","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"strategy_1_2","parentNodeId":"assess_1","group":"PS0~1、肺部病灶为T4或N2","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"strategy_1_1","parentNodeId":"assess_1","group":"PS0~1、肺部病变为非N2且可完全性切除","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"strategy_1_3_a0","parentNodeId":"strategy_1_3","group":"EGFR突变阳性","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"strategy_2_2","parentNodeId":"assess_2","group":"PS0~1、肺部病灶为T4或N2","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"strategy_2_1","parentNodeId":"assess_2","group":"PS0~1、肺部病变为非N2且可完全性切除","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"assess_3_2","parentNodeId":"IV","group":"ALK融合基因阳性","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"assess_3_3","parentNodeId":"IV","group":"ROS1融合基因阳性","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}},{"id":"assess_3_5","parentNodeId":"IV","group":"无驱动基因、鳞癌","nodeTitle":"建议进行多科学查访后，做出选择：","nodeNote":"","nodes":{}},{"id":"assess_3_4","parentNodeId":"IV","group":"无驱动基因、非鳞癌","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"commit","nodes":{}},{"id":"assess_3_1","parentNodeId":"IV","group":"EGFR突变阳性","nodeTitle":"根据患者情况，请做出选择：","nodeNote":"","nodes":{}}],"links":[{"target":"assess_2","source":"IV"},{"target":"assess_1","source":"IV"},{"target":"strategy_1_3","source":"assess_1"},{"target":"strategy_1_3_a1","source":"strategy_1_3"},{"target":"strategy_1_3_a3","source":"strategy_1_3"},{"target":"strategy_1_3_a4","source":"strategy_1_3"},{"target":"strategy_1_3_a2","source":"strategy_1_3"},{"target":"strategy_1_2","source":"assess_1"},{"target":"strategy_1_1","source":"assess_1"},{"target":"strategy_1_3_a0","source":"strategy_1_3"},{"target":"strategy_2_2","source":"assess_2"},{"target":"strategy_2_1","source":"assess_2"},{"target":"assess_3_2","source":"IV"},{"target":"assess_3_3","source":"IV"},{"target":"assess_3_5","source":"IV"},{"target":"assess_3_4","source":"IV"},{"target":"assess_3_1","source":"IV"}]}}';
 var startData = '{"result":{"nodes":[{"id":"root","group":"根节点","nodeNote":"nodeNote","nodeTitle":"nodeTitle"}],"links": []}}';
  var token =   sessionStorage.getItem("token");
//alert(token);  
if(token != null){
	startData = token;
}
debugger;
 var jsonD3 = $.parseJSON( startData );
		//console.log(jsonD3);
    



